<!DOCTYPE html>
<html>
<head>
   <meta charset="UTF-8">
   <title>Memorial</title>
   <link rel="stylesheet" href="styles.css">
</head>
<body>
   <header>
      <h1>Memorial</h1>
   </header>
   <main>
      <button id="cloud-login-button">Cloud Login</button>
      <button id="add-note-button">Add Note</button>
      <button id="record-audio-button">Record Audio</button>
      <button id="freehand-drawing-button">Freehand Drawing</button>
      <div id="note-container"></div>
   </main>
   <footer>
      <p>© 2023 Memorial. All rights reserved.</p>
   </footer>
   <script src="script.js"></script>
</body>
</html>
